version: '3.8'

services:
  db:
    image: postgres:15
    container_name: shorty-db
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - shorty-net

volumes:
  db_data: 

networks:
  shorty-net:
